FROM osrf/ros:noetic-desktop-full-focal

ADD src /basic_dev/src/
ADD setup.bash /

RUN chmod +x /setup.bash

USER root

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=noetic

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-catkin-tools \
    ros-noetic-geographic-msgs \
    ros-noetic-tf2-sensor-msgs \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-image-transport \
    ros-noetic-cv-bridge \
    libopencv-dev \
    net-tools \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /basic_dev/
RUN . /opt/ros/${ROS_DISTRO}/setup.sh \
 && catkin_make --only-pkg-with-deps airsim_ros \
 && . devel/setup.sh \
 && catkin_make --only-pkg-with-deps basic_dev

ENTRYPOINT [ "/setup.bash" ]
